export const mockCanvasConfigure = {
  mode: 'edit',
  componentList: [
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '贷中运营概要',
        color: 'rgba(255,255,255,1)',
        fontSize: 50,
        left: 840,
        top: 41,
        height: 81,
        width: 328,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '5601eb2f-8441-485b-9cc3-20b95c1c9f15',
    },
    {
      name: '装饰边框',
      type: 'BorderBox',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 523,
        height: 400,
        left: 1354,
        top: 143,
        classType: 'BorderBox10',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        {
          key: 'classType',
          name: '装饰边框类别',
          type: 'Select',
          options: [
            { label: '类别1', value: 'BorderBox1' },
            { label: '类别2', value: 'BorderBox2' },
            { label: '类别3', value: 'BorderBox3' },
            { label: '类别4', value: 'BorderBox4' },
            { label: '类别5', value: 'BorderBox5' },
            { label: '类别6', value: 'BorderBox6' },
            { label: '类别7', value: 'BorderBox7' },
            { label: '类别8', value: 'BorderBox8' },
            { label: '类别9', value: 'BorderBox9' },
            { label: '类别10', value: 'BorderBox10' },
            { label: '类别11', value: 'BorderBox11' },
            { label: '类别12', value: 'BorderBox12' },
            { label: '类别13', value: 'BorderBox13' },
          ],
        },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'f2c8be62-e290-4b47-aa83-c06694e59dfe',
    },
    {
      name: '装饰边框',
      type: 'BorderBox',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 806,
        height: 400,
        left: 498,
        top: 139,
        classType: 'BorderBox10',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        {
          key: 'classType',
          name: '装饰边框类别',
          type: 'Select',
          options: [
            { label: '类别1', value: 'BorderBox1' },
            { label: '类别2', value: 'BorderBox2' },
            { label: '类别3', value: 'BorderBox3' },
            { label: '类别4', value: 'BorderBox4' },
            { label: '类别5', value: 'BorderBox5' },
            { label: '类别6', value: 'BorderBox6' },
            { label: '类别7', value: 'BorderBox7' },
            { label: '类别8', value: 'BorderBox8' },
            { label: '类别9', value: 'BorderBox9' },
            { label: '类别10', value: 'BorderBox10' },
            { label: '类别11', value: 'BorderBox11' },
            { label: '类别12', value: 'BorderBox12' },
            { label: '类别13', value: 'BorderBox13' },
          ],
        },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'e0d80727-a8d2-4c27-98a7-f7e178ead320',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '大盘',
        color: 'rgba(255,255,255,1)',
        fontSize: 30,
        left: 532,
        top: 168,
        height: 101,
        width: 36,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '8c033368-5cc5-41e0-a319-93dcafc5eaaf',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '贷款余额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 611,
        top: 154,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'b4f01bbe-f5d0-42b5-89bc-0c607f8d47fa',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '授信总额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 793,
        top: 154,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '8db161ba-db36-43bc-af2c-cd81f1be3b8b',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '授信总额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 964,
        top: 154,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'd3885809-0b96-45be-9b70-378a9f7ee4d3',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '客户数',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 1142,
        top: 154,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '9e6dc8ff-4216-4114-b4eb-588b312f88a0',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '483万',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 1143,
        top: 200,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '1700147a-4c26-4b55-9778-56526ff7d935',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '55.33%',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 966,
        top: 200,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'afb524fc-a092-48c9-865f-5ff9fb7b7bd5',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '432亿',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 796,
        top: 200,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'c2e58cb5-a7d1-4f70-8904-7f380a1ddaa5',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '653亿',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 619,
        top: 200,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '2fde7cd0-f5fd-4bea-aa7f-d4251c0cb68a',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '网e贷',
        color: 'rgba(255,255,255,1)',
        fontSize: 30,
        left: 530,
        top: 275,
        height: 102,
        width: 60,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'aac2b03d-60d2-440e-83b6-bf9ec3987713',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '普惠贷',
        color: 'rgba(255,255,255,1)',
        fontSize: 30,
        left: 521,
        top: 400,
        height: 93,
        width: 62,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '3041a3e7-6d4a-40ac-8ac3-e150721a0120',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '653亿',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 624,
        top: 325,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'aa951f56-e98b-4287-bf9a-72837f89f111',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '653亿',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 793,
        top: 322,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '4e370c57-28e2-437d-9250-d42227ec5893',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '贷款余额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 621,
        top: 400,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '9af20189-7e27-4492-948a-61cd3637c165',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '授信总额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 788,
        top: 261,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '507fd6d3-65f2-45eb-84e3-f7cdb9dcfa00',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '授信总额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 956,
        top: 263,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '1ce28005-918c-4220-a0eb-7634e7d4a087',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '客户数',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 1144,
        top: 260,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'f5d36297-964e-47f3-b76b-acc840613c49',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '483万',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 1139,
        top: 314,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '2a998f0c-e533-4c76-a4bf-0fab4d1fe484',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '贷款余额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 613,
        top: 265,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '9e0b13b4-492f-4fe5-a71a-0c3f046a7331',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '授信总额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 787,
        top: 400,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '0f646ad3-bad6-49fd-b471-04d86f19fa21',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '授信总额',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 948,
        top: 400,
        height: 46,
        width: 130,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '5cb47f02-45ca-45d6-8db5-2bf3fac5136f',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '客户数',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 1133,
        top: 400,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '6e895fde-41df-4656-a855-1fe1ef258123',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '483万',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 1135,
        top: 451,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'a49285f9-69ac-49c5-b3b2-e255a268a976',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '55.33%',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 960,
        top: 320,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '48f95745-dbdd-472d-bc4b-5d96b397a965',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '55.33%',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 956,
        top: 451,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'b832b2b6-940d-4561-98e8-2fa0d1f539c0',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '653亿',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 799,
        top: 449,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '89c181e4-72ad-45ba-9379-5c160b9caaaf',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '653亿',
        color: 'rgba(255,255,255,1)',
        fontSize: 26,
        left: 627,
        top: 449,
        height: 46,
        width: 86,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '750f62dc-6fd5-4672-ba50-ee183265e839',
    },
    {
      name: '装饰边框',
      type: 'BorderBox',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 1261,
        height: 355,
        left: 42,
        top: 567,
        classType: 'BorderBox8',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        {
          key: 'classType',
          name: '装饰边框类别',
          type: 'Select',
          options: [
            { label: '类别1', value: 'BorderBox1' },
            { label: '类别2', value: 'BorderBox2' },
            { label: '类别3', value: 'BorderBox3' },
            { label: '类别4', value: 'BorderBox4' },
            { label: '类别5', value: 'BorderBox5' },
            { label: '类别6', value: 'BorderBox6' },
            { label: '类别7', value: 'BorderBox7' },
            { label: '类别8', value: 'BorderBox8' },
            { label: '类别9', value: 'BorderBox9' },
            { label: '类别10', value: 'BorderBox10' },
            { label: '类别11', value: 'BorderBox11' },
            { label: '类别12', value: 'BorderBox12' },
            { label: '类别13', value: 'BorderBox13' },
          ],
        },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '7ba36158-c35f-4264-b387-e155ceb4a02f',
    },
    {
      name: '折线图',
      type: 'Line',
      icon: 'icon-xianxingtu',
      category: 'control',
      config: {
        width: 320,
        height: 263,
        dataType: 'api',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: 'Mon', yAxis: 0.8269903069630793 },
          { xAxis: 'Tue', yAxis: 0.2462620175492285 },
          { xAxis: 'Wed', yAxis: 0.8370002782820916 },
          { xAxis: 'Thu', yAxis: 0.4370129735593826 },
          { xAxis: 'Fri', yAxis: 0.39044128094629116 },
          { xAxis: 'Sat', yAxis: 0.42393355098657826 },
          { xAxis: 'Sun', yAxis: 0.3525947729189942 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        left: 51,
        top: 656,
        isPolling: true,
        pollingInterval: 3000,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '148155cd-b219-4f86-a995-512c2a379672',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        text: '贷中风险模型监控',
        color: 'rgba(255,255,255,1)',
        fontSize: 30,
        left: 529,
        top: 592,
        height: 50,
        width: 257,
      },
      baseConfig: [
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'f4132d10-81de-4847-84fc-d36bcd2785da',
    },
    {
      name: '折线图',
      type: 'Line',
      icon: 'icon-xianxingtu',
      category: 'control',
      config: {
        width: 320,
        height: 263,
        dataType: 'api',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: 'Mon', yAxis: 0.8269903069630793 },
          { xAxis: 'Tue', yAxis: 0.2462620175492285 },
          { xAxis: 'Wed', yAxis: 0.8370002782820916 },
          { xAxis: 'Thu', yAxis: 0.4370129735593826 },
          { xAxis: 'Fri', yAxis: 0.39044128094629116 },
          { xAxis: 'Sat', yAxis: 0.42393355098657826 },
          { xAxis: 'Sun', yAxis: 0.3525947729189942 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        left: 370,
        top: 656,
        isPolling: true,
        pollingInterval: 3000,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '98c3fd36-d168-47e1-8b5d-69ca0caecf28',
    },
    {
      name: '折线图',
      type: 'Line',
      icon: 'icon-xianxingtu',
      category: 'control',
      config: {
        width: 320,
        height: 263,
        dataType: 'api',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: 'Mon', yAxis: 0.8269903069630793 },
          { xAxis: 'Tue', yAxis: 0.2462620175492285 },
          { xAxis: 'Wed', yAxis: 0.8370002782820916 },
          { xAxis: 'Thu', yAxis: 0.4370129735593826 },
          { xAxis: 'Fri', yAxis: 0.39044128094629116 },
          { xAxis: 'Sat', yAxis: 0.42393355098657826 },
          { xAxis: 'Sun', yAxis: 0.3525947729189942 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        left: 686,
        top: 656,
        isPolling: true,
        pollingInterval: 3000,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'aebba588-8f3b-4f55-95a6-3a48635e2fcc',
    },
    {
      name: '折线图',
      type: 'Line',
      icon: 'icon-xianxingtu',
      category: 'control',
      config: {
        width: 295,
        height: 263,
        dataType: 'api',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: 'Mon', yAxis: 0.8269903069630793 },
          { xAxis: 'Tue', yAxis: 0.3 },
          { xAxis: 'Wed', yAxis: 0.4 },
          { xAxis: 'Thu', yAxis: 0.1 },
          { xAxis: 'Fri', yAxis: 0.8 },
          { xAxis: 'Sat', yAxis: 0.6 },
          { xAxis: 'Sun', yAxis: 0.3525947729189942 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        left: 1004,
        top: 656,
        isPolling: true,
        pollingInterval: 3000,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '8c7f4fa0-7960-4a0b-8137-3b365955b0e4',
    },
    {
      name: '装饰边框',
      type: 'BorderBox',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 522,
        height: 352,
        left: 1353,
        top: 567,
        classType: 'BorderBox8',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        {
          key: 'classType',
          name: '装饰边框类别',
          type: 'Select',
          options: [
            { label: '类别1', value: 'BorderBox1' },
            { label: '类别2', value: 'BorderBox2' },
            { label: '类别3', value: 'BorderBox3' },
            { label: '类别4', value: 'BorderBox4' },
            { label: '类别5', value: 'BorderBox5' },
            { label: '类别6', value: 'BorderBox6' },
            { label: '类别7', value: 'BorderBox7' },
            { label: '类别8', value: 'BorderBox8' },
            { label: '类别9', value: 'BorderBox9' },
            { label: '类别10', value: 'BorderBox10' },
            { label: '类别11', value: 'BorderBox11' },
            { label: '类别12', value: 'BorderBox12' },
            { label: '类别13', value: 'BorderBox13' },
          ],
        },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '230360f0-1e91-4014-aa71-04544f339078',
    },
    {
      name: '装饰边框',
      type: 'BorderBox',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 419,
        height: 400,
        left: 42,
        top: 139,
        classType: 'BorderBox10',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        {
          key: 'classType',
          name: '装饰边框类别',
          type: 'Select',
          options: [
            { label: '类别1', value: 'BorderBox1' },
            { label: '类别2', value: 'BorderBox2' },
            { label: '类别3', value: 'BorderBox3' },
            { label: '类别4', value: 'BorderBox4' },
            { label: '类别5', value: 'BorderBox5' },
            { label: '类别6', value: 'BorderBox6' },
            { label: '类别7', value: 'BorderBox7' },
            { label: '类别8', value: 'BorderBox8' },
            { label: '类别9', value: 'BorderBox9' },
            { label: '类别10', value: 'BorderBox10' },
            { label: '类别11', value: 'BorderBox11' },
            { label: '类别12', value: 'BorderBox12' },
            { label: '类别13', value: 'BorderBox13' },
          ],
        },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '4799808d-2faa-4e8c-81b4-7aad071e80db',
    },
    {
      name: '饼图',
      type: 'Pie',
      icon: 'icon-xianxingtu',
      category: 'control',
      config: {
        width: 389,
        height: 369,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '合规投诉', yAxis: 0.62 },
          { xAxis: '催收投诉', yAxis: 0.18 },
          { xAxis: '产品服务投诉', yAxis: 0.2 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        left: 61,
        top: 155,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '6ea158bc-d91f-430a-b3b0-22073f4b820b',
    },
    {
      name: '轮播表',
      type: 'ScrollBoard',
      icon: 'icon-shanxingtu',
      category: 'control',
      config: {
        width: 591,
        height: 178,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: {
          data: [
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
          ],
        },
        left: 45,
        top: 939,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'fbb825ef-0ece-4bed-8427-5a78a6e47b36',
    },
    {
      name: '柱状图',
      type: 'Bar',
      icon: 'icon-zhuzhuangtu',
      category: 'control',
      config: {
        width: 479,
        height: 314,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '大盘', yAxis: 100 },
          { xAxis: 'xx贷', yAxis: 60 },
          { xAxis: 'xx贷2', yAxis: 30 },
          { xAxis: 'xx贷3', yAxis: 20 },
          { xAxis: 'xx贷4', yAxis: 70 },
          { xAxis: 'xx贷5', yAxis: 40 },
          { xAxis: 'xx贷6', yAxis: 50 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        left: 1368,
        top: 578,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'a7a34a86-655a-4ad7-aa80-a20d65be02a1',
    },
    {
      name: '堆积柱状图',
      type: 'StackBar',
      icon: 'icon-zhuzhuangtu',
      category: 'control',
      config: {
        width: 479,
        height: 339,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '5%', yAxis: '200', series: '大盘' },
          { xAxis: '5%', yAxis: '100', series: 'xx贷' },
          { xAxis: '5%', yAxis: '200', series: 'xx贷款2' },
          { xAxis: '5%-8%', yAxis: '25', series: '大盘' },
          { xAxis: '5%-8%', yAxis: '125', series: 'xx贷' },
          { xAxis: '5%-8%', yAxis: '100', series: 'xx贷款2' },
          { xAxis: '12%-15%', yAxis: '190', series: '大盘' },
          { xAxis: '12%-15%', yAxis: '110', series: 'xx贷' },
          { xAxis: '12%-15%', yAxis: '170', series: 'xx贷款2' },
          { xAxis: '15%-18%', yAxis: '90', series: '大盘' },
          { xAxis: '15%-18%', yAxis: '60', series: 'xx贷' },
          { xAxis: '15%-18%', yAxis: '70', series: 'xx贷款2' },
          { xAxis: '18%-20%', yAxis: '240', series: '大盘' },
          { xAxis: '18%-20%', yAxis: '170', series: 'xx贷' },
          { xAxis: '18%-20%', yAxis: '280', series: 'xx贷款2' },
          { xAxis: '20%-24%', yAxis: '420', series: '大盘' },
          { xAxis: '20%-24%', yAxis: '190', series: 'xx贷' },
          { xAxis: '20%-24%', yAxis: '390', series: 'xx贷款2' },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
          { key: 'series', mapping: '' },
        ],
        left: 1376,
        top: 180,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '84779621-8388-4a1d-a391-87cd93ada99a',
    },
    {
      name: '装饰边框',
      type: 'BorderBox',
      icon: 'icon-waibiankuang',
      category: 'control',
      config: {
        width: 591,
        height: 141,
        left: 704,
        top: 0,
        classType: 'BorderBox11',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        {
          key: 'classType',
          name: '装饰边框类别',
          type: 'Select',
          options: [
            { label: '类别1', value: 'BorderBox1' },
            { label: '类别2', value: 'BorderBox2' },
            { label: '类别3', value: 'BorderBox3' },
            { label: '类别4', value: 'BorderBox4' },
            { label: '类别5', value: 'BorderBox5' },
            { label: '类别6', value: 'BorderBox6' },
            { label: '类别7', value: 'BorderBox7' },
            { label: '类别8', value: 'BorderBox8' },
            { label: '类别9', value: 'BorderBox9' },
            { label: '类别10', value: 'BorderBox10' },
            { label: '类别11', value: 'BorderBox11' },
            { label: '类别12', value: 'BorderBox12' },
            { label: '类别13', value: 'BorderBox13' },
          ],
        },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'a3a06875-15c9-43b5-a0eb-15862a41590d',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: { width: 88, height: 32, left: 192, top: 137, zIndex: 44 },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'Img', name: '图片', type: 'Select' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'c63479f5-1747-4c21-af1c-f71f8597a804',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: { width: 1911, height: 840, left: 0, top: 101, zIndex: 0 },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'Img', name: '图片', type: 'Select' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '5bf54863-e19b-493a-b561-18c39e3a82eb',
    },
  ],
  width: 1920,
  height: 1080,
  curComponentConfig: {
    name: '折线图',
    type: 'Line',
    icon: 'icon-xianxingtu',
    category: 'CHART',
    config: {
      width: 200,
      height: 200,
      dataType: 'api',
      requestUrl:
        'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
      dataSource: [
        { xAxis: 'Mon', yAxis: 0.3727722807405265 },
        { xAxis: 'Tue', yAxis: 0.8860584756559087 },
        { xAxis: 'Wed', yAxis: 0.20343226645268353 },
        { xAxis: 'Thu', yAxis: 0.08638235966979524 },
        { xAxis: 'Fri', yAxis: 0.3877376622036981 },
        { xAxis: 'Sat', yAxis: 0.0215669203802471 },
        { xAxis: 'Sun', yAxis: 0.48371983928255147 },
      ],
      dataMapping: [
        { key: 'xAxis', mapping: '' },
        { key: 'yAxis', mapping: '' },
      ],
      left: 154,
      top: 0,
      zIndex: 46,
    },
    baseConfig: [
      { key: 'componentName', name: '名称', type: 'Text' },
      { key: 'width', name: '宽度', type: 'Number' },
      { key: 'height', name: '高度', type: 'Number' },
      { key: 'top', name: '纵向偏移', type: 'Number' },
      { key: 'left', name: '横向偏移', type: 'Number' },
      { key: 'zIndex', name: '组件层级', type: 'Number' },
      { key: 'title', name: '标题', type: 'Text' },
      { key: 'titleColor', name: '标题颜色', type: 'Color' },
      { key: 'legendTextColor', name: '图例文字颜色', type: 'Color' },
      { key: 'legendTextSize', name: '图例文字大小', type: 'Number' },
      { key: 'color', name: '轴线/柱颜色', type: 'Color' },
      { key: 'series', name: '系列', type: 'TabList' },
    ],
    dataConfig: [
      {
        key: 'dataType',
        name: '数据类型',
        type: 'Select',
        options: [
          { label: '静态数据', value: 'static' },
          { label: '内置指标', value: 'quota' },
          { label: 'API', value: 'api' },
        ],
      },
      { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
      {
        key: 'method',
        name: '请求方式',
        type: 'Select',
        options: [
          { label: 'GET', value: 'get' },
          { label: 'POST', value: 'post' },
        ],
        defaultValue: 'get',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['api'] }],
        },
      },
      {
        key: 'requestUrl',
        name: 'URL',
        type: 'TextArea',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['api'] }],
        },
      },
      {
        key: 'dataQuota',
        name: '数据指标',
        type: 'DataQuotaSelector',
        options: [],
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
        },
      },
      {
        key: 'isPolling',
        name: '定时刷新',
        type: 'Switch',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
        },
      },
      {
        key: 'pollingInterval',
        name: '刷新时间',
        type: 'Number',
        dependencies: {
          items: [{ dependKey: 'isPolling', dependValues: [true] }],
        },
      },
      {
        key: 'dataSource',
        name: '数据源',
        type: 'MonacoEditor',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['static'] }],
        },
      },
    ],
    styleConfig: [
      { key: 'color', name: '标题颜色', type: 'Color' },
      { key: 'fontSize', name: '文字大小', type: 'Number' },
    ],
    eventConfig: [{}],
    componentId: '1bb586e0-f86e-4a0e-a016-8039c698b49c',
  },
  canvasConfig: {
    width: 1920,
    height: 1680,
    backgroundColor: 'rgba(14,23,31,1)',
  },
};
