const page2 = {
  mode: 'edit',
  componentList: [
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 467,
        height: 41,
        left: 13,
        top: 136,
        zIndex: 45,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929390422-ERkLZiJB.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '7dd6582e-8bc6-4d3f-8521-a9177ebd4ea5',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 1920,
        height: 86,
        left: 0,
        top: 0,
        zIndex: 12,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929391169-7qcX5iQR.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'db4c6579-5041-4d24-ba27-3eafc84b9f27',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 216,
        height: 49,
        text: '中国工商银行',
        color: 'rgba(255,255,255,1)',
        fontSize: 34,
        left: 848,
        top: 16,
        zIndex: 12,
        componentName: '',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '94cbfce1-2c44-4399-8441-98a497aa0af9',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 1920,
        height: 1080,
        left: 0,
        top: 0,
        zIndex: 0,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929396172-8KkT24og.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '250dc3bd-af6a-484d-a4f8-c2be2bc7546d',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 60,
        height: 50,
        left: 7,
        top: 80,
        zIndex: 14,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929397797-Av8gcZ5j.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '04407146-bc3f-4dce-8beb-611050869bff',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 60,
        height: 50,
        left: 1859,
        top: 80,
        zIndex: 15,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929397112-HZxN3_dO.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '015c52ee-c9ab-4455-9267-071861ac723a',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 530,
        height: 70,
        left: 727,
        top: 704,
        zIndex: 16,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929393526-FqAYJP4f.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '58f90bb8-25f9-416b-a823-7f07c2ff6bef',
    },
    {
      name: '轮播表',
      type: 'ScrollBoard',
      icon: 'icon-lunbobiaoge',
      category: 'control',
      config: {
        width: 662,
        height: 182,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: {
          header: ['列1', '列2', '列3'],
          data: [
            ['四川智筹催收公司', '金额:57058005.00人民币', '案件:506件'],
            ['四川信发有限公司', '金额:48058795.00人民币', '案件:304件'],
            ['四川无极有限公司', '金额:46055798.00人民币', '案件:287件'],
            ['四川信义有限公司', '金额:38059875.00人民币', '案件:267件'],
            ['前道催收有限公司', '金额:36068764.00人民币', '案件:278件'],
            ['四川石鹏催收公司', '金额:32058005.00人民币', '案件:306件'],
            ['四川武利催收公司', '金额:28058005.00人民币', '案件:357件'],
          ],
        },
        globalConfig: { index: true, rowNum: 5, waitTime: 2000 },
        headerConfig: {
          headerHeight: 30,
          headerBGC: 'rgba(10, 115, 217, 0.2)',
          headerVisible: false,
        },
        lineConfig: {
          oddRowBGC: 'rgba(10, 115, 255, 0)',
          evenRowBGC: 'rgba(9,109,217,0.3)',
        },
        columns: [
          { columnWidth: 50, textStyle: { color: '#fff', fontSize: 14 } },
          { columnWidth: 200, textStyle: { color: '#fff', fontSize: 14 } },
          { columnWidth: 200, textStyle: { color: '#fff', fontSize: 14 } },
          { columnWidth: 200, textStyle: { color: '#fff', fontSize: 14 } },
        ],
        left: 672,
        top: 789,
        zIndex: 17,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'globalConfig',
          name: '全局设定',
          type: 'Group',
          config: [
            { key: 'index', name: '显示序列号', type: 'Switch' },
            { key: 'rowNum', name: '表格行数', type: 'Number' },
            { key: 'waitTime', name: '轮播时间', type: 'Number' },
          ],
        },
        {
          key: 'headerConfig',
          name: '表头',
          type: 'Group',
          config: [
            { key: 'headerVisible', name: '是否显示', type: 'Switch' },
            { key: 'headerHeight', name: '表头行高', type: 'Number' },
            { key: 'headerBGC', name: '背景颜色', type: 'Color' },
          ],
        },
        {
          key: 'lineConfig',
          name: '行配置',
          type: 'Group',
          config: [
            { key: 'oddRowBGC', name: '奇数行背景色', type: 'Color' },
            { key: 'evenRowBGC', name: '偶数行背景色', type: 'Color' },
          ],
        },
        {
          key: 'columns',
          name: '自定义列',
          type: 'TabList',
          initialValue: {
            columnWidth: 200,
            textStyle: { color: '#fff', fontSize: 12 },
          },
          config: [
            { key: 'columnWidth', name: '列宽度', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '75b24e49-9530-432c-ade9-7a371de2dde3',
    },
    {
      name: '中国地图',
      type: 'ChinaMap',
      icon: 'icon-zhuzhuangtu',
      category: 'CHART',
      config: { width: 764, height: 491, left: 583, top: 353, zIndex: 1 },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'title', name: '文字', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'options', name: '选项', type: 'List' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'fecdd452-9bbd-4796-b179-25d58f16450b',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 246,
        height: 53,
        text: '催收机构排名',
        color: 'rgba(254, 250, 250, 1)',
        fontSize: 30,
        left: 888,
        top: 715,
        zIndex: 16,
        componentName: '',
        backgroundColor: 'rgba(158, 38, 38, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'ca00d6a0-c346-4a75-9d9f-c19672f842ef',
    },
    {
      name: '折线图',
      type: 'Line',
      chartType: 'line',
      icon: 'icon-xianxingtu',
      category: 'CHART',
      config: {
        width: 400,
        height: 214,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '2022.1', yAxis: 5610 },
          { xAxis: '2022.2', yAxis: 4561 },
          { xAxis: '2022.3', yAxis: 4358 },
          { xAxis: '2022.4', yAxis: 6725 },
          { xAxis: '2022.5', yAxis: 6871 },
          { xAxis: '2022.6', yAxis: 5514 },
          { xAxis: '2022.7', yAxis: 3467 },
          { xAxis: '2022.8', yAxis: 3800 },
          { xAxis: '2022.9', yAxis: 8700 },
          { xAxis: '2022.10', yAxis: 4974 },
          { xAxis: '2022.11', yAxis: 6800 },
          { xAxis: '2022.12', yAxis: 8647 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 1498,
        top: 759,
        zIndex: 16,
        series: [
          {
            areaStyle: {
              color:
                'linear-gradient(90deg, RGBA(2,0,36,1) 0%, rgba(0,212,255,1) 100%)',
            },
          },
        ],
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
        {
          key: 'grid',
          name: '网格',
          type: 'Group',
          config: [
            { key: 'left', name: '左边距', type: 'Number' },
            { key: 'top', name: '上边距', type: 'Number' },
            { key: 'right', name: '右边距', type: 'Number' },
            { key: 'bottom', name: '下边距', type: 'Number' },
          ],
        },
        {
          key: 'series',
          name: '系列',
          type: 'TabList',
          config: [
            {
              key: 'lineStyle',
              name: '线条样式',
              type: 'Group',
              config: [
                { key: 'color', name: '线条颜色', type: 'Color' },
                { key: 'width', name: '线条宽度', type: 'Number' },
                {
                  key: 'type',
                  name: '线条类型',
                  type: 'Select',
                  options: [
                    { label: '实线', value: 'solid' },
                    { label: '虚线', value: 'dashed' },
                  ],
                },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'itemStyle',
              name: '折线拐点样式',
              type: 'Group',
              config: [
                { key: 'color', name: '折线拐点颜色', type: 'Color' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'areaStyle',
              name: '折线区域样式',
              type: 'Group',
              config: [
                { key: 'color', name: '区域颜色', type: 'GradientColor' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            { key: 'smooth', name: '平滑曲线', type: 'Number' },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '74feec66-debb-4e02-92b2-b8a42cbc03a5',
    },
    {
      name: '环形图',
      type: 'RingChart',
      chartType: 'pie',
      icon: 'icon-shanxingtu',
      category: 'CHART',
      config: {
        width: 473,
        height: 440,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '融e贷', yAxis: 1 },
          { xAxis: '车业务', yAxis: 1 },
          { xAxis: '卡分期', yAxis: 1 },
          { xAxis: '小微业务', yAxis: 1 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 55,
        top: 200,
        zIndex: 18,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '871d825d-d6a3-4091-b479-fac1a6463155',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 137,
        height: 29,
        text: '产品组成',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 16,
        left: 47,
        top: 142,
        zIndex: 46,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '31f3ddb7-fc90-42bf-94b7-fe16e8a0cdbc',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 400,
        height: 41,
        left: 1498,
        top: 113,
        zIndex: 45,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929390422-ERkLZiJB.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'd82b2213-b6b1-4d98-a0b1-f649c1520d9f',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 1858,
        height: 61,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929391862-NoETDPhi.png',
        left: 40,
        top: 1001,
        zIndex: 20,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '31447d5b-7895-4606-a43c-475a848d448b',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 147,
        height: 31,
        text: '状态预警',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 16,
        left: 1528,
        top: 121,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'b369f4aa-a807-432a-a7c6-8cab2fa62fdf',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 243,
        height: 27,
        text: '2022年其他金融产品各月贷款人数',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 1588,
        top: 972,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '4ebd6ed8-1286-46b8-b68b-d77adab72829',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 467,
        height: 41,
        left: 29,
        top: 630,
        zIndex: 45,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929390422-ERkLZiJB.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'adb3ebff-93a7-4c12-90e7-39c9b1ecc4ef',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 149,
        height: 29,
        text: '近7日贷后检查时序',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 16,
        left: 73,
        top: 636,
        zIndex: 46,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '6c441a5d-53c1-4c9c-b04b-743c69c7a377',
    },
    {
      name: '环形图',
      type: 'RingChart',
      chartType: 'pie',
      icon: 'icon-shanxingtu',
      category: 'CHART',
      config: {
        width: 422,
        height: 315,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '失联', yAxis: 18050 },
          { xAxis: '反催收倾向', yAxis: 6680 },
          { xAxis: '疑似欺诈', yAxis: 3635 },
          { xAxis: '投诉倾向', yAxis: 1600 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 1498,
        top: 164,
        zIndex: 18,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '265a226d-3a47-4242-8a7d-377a0b6f86e4',
    },
    {
      name: '折线图',
      type: 'Line',
      chartType: 'line',
      icon: 'icon-xianxingtu',
      category: 'CHART',
      config: {
        width: 245,
        height: 150,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '2.06', yAxis: 50 },
          { xAxis: '2.07', yAxis: 61 },
          { xAxis: '2.08', yAxis: 48 },
          { xAxis: '2.09', yAxis: 87 },
          { xAxis: '2.10', yAxis: 56 },
          { xAxis: '2.11', yAxis: 94 },
          { xAxis: '2.12', yAxis: 77 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 31,
        top: 674,
        zIndex: 21,
        series: [
          {
            areaStyle: {
              color:
                'linear-gradient(90deg, RGBA(2,0,36,1) 0%, rgba(0,212,255,1) 100%)',
            },
          },
        ],
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
        {
          key: 'grid',
          name: '网格',
          type: 'Group',
          config: [
            { key: 'left', name: '左边距', type: 'Number' },
            { key: 'top', name: '上边距', type: 'Number' },
            { key: 'right', name: '右边距', type: 'Number' },
            { key: 'bottom', name: '下边距', type: 'Number' },
          ],
        },
        {
          key: 'series',
          name: '系列',
          type: 'TabList',
          config: [
            {
              key: 'lineStyle',
              name: '线条样式',
              type: 'Group',
              config: [
                { key: 'color', name: '线条颜色', type: 'Color' },
                { key: 'width', name: '线条宽度', type: 'Number' },
                {
                  key: 'type',
                  name: '线条类型',
                  type: 'Select',
                  options: [
                    { label: '实线', value: 'solid' },
                    { label: '虚线', value: 'dashed' },
                  ],
                },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'itemStyle',
              name: '折线拐点样式',
              type: 'Group',
              config: [
                { key: 'color', name: '折线拐点颜色', type: 'Color' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'areaStyle',
              name: '折线区域样式',
              type: 'Group',
              config: [
                { key: 'color', name: '区域颜色', type: 'GradientColor' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            { key: 'smooth', name: '平滑曲线', type: 'Number' },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'e2fafb29-c774-4f18-8417-f6f72ce593b4',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 66,
        height: 26,
        text: '催收总数',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 111,
        top: 824,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '6e9ff150-7c1c-4ac9-880b-0a5861547a0c',
    },
    {
      name: '折线图',
      type: 'Line',
      chartType: 'line',
      icon: 'icon-xianxingtu',
      category: 'CHART',
      config: {
        width: 245,
        height: 150,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '2.06', yAxis: 46 },
          { xAxis: '2.07', yAxis: 33 },
          { xAxis: '2.08', yAxis: 64 },
          { xAxis: '2.09', yAxis: 48 },
          { xAxis: '2.10', yAxis: 44 },
          { xAxis: '2.11', yAxis: 56 },
          { xAxis: '2.12', yAxis: 38 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 280,
        top: 674,
        zIndex: 21,
        series: [
          {
            areaStyle: {
              color:
                'linear-gradient(90deg, RGBA(2,0,36,1) 0%, rgba(0,212,255,1) 100%)',
            },
          },
        ],
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
        {
          key: 'grid',
          name: '网格',
          type: 'Group',
          config: [
            { key: 'left', name: '左边距', type: 'Number' },
            { key: 'top', name: '上边距', type: 'Number' },
            { key: 'right', name: '右边距', type: 'Number' },
            { key: 'bottom', name: '下边距', type: 'Number' },
          ],
        },
        {
          key: 'series',
          name: '系列',
          type: 'TabList',
          config: [
            {
              key: 'lineStyle',
              name: '线条样式',
              type: 'Group',
              config: [
                { key: 'color', name: '线条颜色', type: 'Color' },
                { key: 'width', name: '线条宽度', type: 'Number' },
                {
                  key: 'type',
                  name: '线条类型',
                  type: 'Select',
                  options: [
                    { label: '实线', value: 'solid' },
                    { label: '虚线', value: 'dashed' },
                  ],
                },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'itemStyle',
              name: '折线拐点样式',
              type: 'Group',
              config: [
                { key: 'color', name: '折线拐点颜色', type: 'Color' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'areaStyle',
              name: '折线区域样式',
              type: 'Group',
              config: [
                { key: 'color', name: '区域颜色', type: 'GradientColor' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            { key: 'smooth', name: '平滑曲线', type: 'Number' },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '06e459ce-995a-4944-8ec5-e8f03f100ab3',
    },
    {
      name: '折线图',
      type: 'Line',
      chartType: 'line',
      icon: 'icon-xianxingtu',
      category: 'CHART',
      config: {
        width: 245,
        height: 150,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '2.06', yAxis: 6057952 },
          { xAxis: '2.07', yAxis: 5468797 },
          { xAxis: '2.08', yAxis: 6978945 },
          { xAxis: '2.09', yAxis: 5089547 },
          { xAxis: '2.10', yAxis: 5476486 },
          { xAxis: '2.11', yAxis: 4687945 },
          { xAxis: '2.12', yAxis: 4876549 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 31,
        top: 845,
        zIndex: 21,
        series: [
          {
            areaStyle: {
              color:
                'linear-gradient(90deg, RGBA(2,0,36,1) 0%, rgba(0,212,255,1) 100%)',
            },
          },
        ],
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
        {
          key: 'grid',
          name: '网格',
          type: 'Group',
          config: [
            { key: 'left', name: '左边距', type: 'Number' },
            { key: 'top', name: '上边距', type: 'Number' },
            { key: 'right', name: '右边距', type: 'Number' },
            { key: 'bottom', name: '下边距', type: 'Number' },
          ],
        },
        {
          key: 'series',
          name: '系列',
          type: 'TabList',
          config: [
            {
              key: 'lineStyle',
              name: '线条样式',
              type: 'Group',
              config: [
                { key: 'color', name: '线条颜色', type: 'Color' },
                { key: 'width', name: '线条宽度', type: 'Number' },
                {
                  key: 'type',
                  name: '线条类型',
                  type: 'Select',
                  options: [
                    { label: '实线', value: 'solid' },
                    { label: '虚线', value: 'dashed' },
                  ],
                },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'itemStyle',
              name: '折线拐点样式',
              type: 'Group',
              config: [
                { key: 'color', name: '折线拐点颜色', type: 'Color' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'areaStyle',
              name: '折线区域样式',
              type: 'Group',
              config: [
                { key: 'color', name: '区域颜色', type: 'GradientColor' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            { key: 'smooth', name: '平滑曲线', type: 'Number' },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'fa096a68-ece8-4f64-a142-9cdcaf3b4014',
    },
    {
      name: '折线图',
      type: 'Line',
      chartType: 'line',
      icon: 'icon-xianxingtu',
      category: 'CHART',
      config: {
        width: 245,
        height: 150,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '2.06', yAxis: 66 },
          { xAxis: '2.07', yAxis: 57 },
          { xAxis: '2.08', yAxis: 72 },
          { xAxis: '2.09', yAxis: 46 },
          { xAxis: '2.10', yAxis: 52 },
          { xAxis: '2.11', yAxis: 39 },
          { xAxis: '2.12', yAxis: 41 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 280,
        top: 845,
        zIndex: 21,
        series: [
          {
            areaStyle: {
              color:
                'linear-gradient(90deg, RGBA(2,0,36,1) 0%, rgba(0,212,255,1) 100%)',
            },
          },
        ],
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
        {
          key: 'grid',
          name: '网格',
          type: 'Group',
          config: [
            { key: 'left', name: '左边距', type: 'Number' },
            { key: 'top', name: '上边距', type: 'Number' },
            { key: 'right', name: '右边距', type: 'Number' },
            { key: 'bottom', name: '下边距', type: 'Number' },
          ],
        },
        {
          key: 'series',
          name: '系列',
          type: 'TabList',
          config: [
            {
              key: 'lineStyle',
              name: '线条样式',
              type: 'Group',
              config: [
                { key: 'color', name: '线条颜色', type: 'Color' },
                { key: 'width', name: '线条宽度', type: 'Number' },
                {
                  key: 'type',
                  name: '线条类型',
                  type: 'Select',
                  options: [
                    { label: '实线', value: 'solid' },
                    { label: '虚线', value: 'dashed' },
                  ],
                },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'itemStyle',
              name: '折线拐点样式',
              type: 'Group',
              config: [
                { key: 'color', name: '折线拐点颜色', type: 'Color' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'areaStyle',
              name: '折线区域样式',
              type: 'Group',
              config: [
                { key: 'color', name: '区域颜色', type: 'GradientColor' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            { key: 'smooth', name: '平滑曲线', type: 'Number' },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'b232d5f5-0b61-4325-b002-7011ae8ba7f0',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 66,
        height: 26,
        text: '回款率',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 365,
        top: 819,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '84ec76c2-765e-438e-8fc9-683459e76cdf',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 66,
        height: 26,
        text: '成本效率',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 366,
        top: 988,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'f1274648-4a97-441f-8d4e-105a9883597a',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 66,
        height: 26,
        text: '回款总数',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 118,
        top: 990,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '3ca452b9-94cd-4830-a4e9-740c147ec510',
    },
  ],
  curComponentConfig: {
    name: '百分比环',
    type: 'PercentRing',
    chartType: 'pie',
    icon: 'icon-shanxingtu',
    category: 'CHART',
    config: {
      width: 286,
      height: 272,
      dataType: 'static',
      requestUrl:
        'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
      dataSource: [
        { xAxis: 'Mon', yAxis: 0.395640700261112 },
        { xAxis: 'Tue', yAxis: 0.14230468269304608 },
        { xAxis: 'Wed', yAxis: 0.306832916878389 },
        { xAxis: 'Thu', yAxis: 0.40341616312243644 },
        { xAxis: 'Fri', yAxis: 0.5564475840540104 },
        { xAxis: 'Sat', yAxis: 0.44661481463160757 },
        { xAxis: 'Sun', yAxis: 0.130491955790758 },
      ],
      dataMapping: [
        { key: 'xAxis', mapping: '' },
        { key: 'yAxis', mapping: '' },
      ],
      grid: { left: 30, right: 30, top: 30, bottom: 30 },
      legend: {
        horizontalPosition: 'auto',
        verticalPosition: 'auto',
        orient: 'horizontal',
        padding: 30,
        itemGap: 20,
        textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
      },
      left: 1161,
      top: 117,
      zIndex: 29,
    },
    baseConfig: [
      { key: 'componentName', name: '名称', type: 'Text' },
      { key: 'width', name: '宽度', type: 'Number' },
      { key: 'height', name: '高度', type: 'Number' },
      { key: 'top', name: '纵向偏移', type: 'Number' },
      { key: 'left', name: '横向偏移', type: 'Number' },
      { key: 'zIndex', name: '组件层级', type: 'Number' },
      {
        key: 'legend',
        name: '图例',
        type: 'Group',
        config: [
          {
            key: 'horizontalPosition',
            name: '水平位置',
            type: 'Select',
            options: [
              { label: '自动', value: 'auto' },
              { label: '左对齐', value: 'left' },
              { label: '居中对齐', value: 'center' },
              { label: '右对齐', value: 'right' },
            ],
          },
          {
            key: 'verticalPosition',
            name: '竖直位置',
            type: 'Select',
            options: [
              { label: '自动', value: 'auto' },
              { label: '顶部对齐', value: 'top' },
              { label: '居中对齐', value: 'center' },
              { label: '底部对齐', value: 'bottom' },
            ],
          },
          {
            key: 'orient',
            name: '朝向',
            type: 'Select',
            options: [
              { label: '垂直', value: 'vertical' },
              { label: '水平', value: 'horizontal' },
            ],
          },
          { key: 'padding', name: '内边距', type: 'Number' },
          { key: 'itemGap', name: '图例项间距', type: 'Number' },
          {
            key: 'textStyle',
            name: '文本样式',
            type: 'Group',
            config: [
              { key: 'color', name: '颜色', type: 'Color' },
              {
                key: 'fontWeight',
                name: '字体粗细',
                type: 'Select',
                options: [
                  { label: 'Normal', value: 'normal' },
                  { label: 'Bold', value: 'bold' },
                  { label: 'Bolder', value: 'bolder' },
                  { label: 100, value: 100 },
                  { label: 200, value: 200 },
                  { label: 300, value: 300 },
                  { label: 400, value: 400 },
                  { label: 500, value: 500 },
                  { label: 600, value: 600 },
                  { label: 700, value: 700 },
                  { label: 800, value: 800 },
                  { label: 900, value: 900 },
                ],
              },
              { key: 'fontSize', name: '字号', type: 'Number' },
            ],
          },
        ],
      },
    ],
    dataConfig: [
      {
        key: 'dataType',
        name: '数据类型',
        type: 'Select',
        options: [
          { label: '静态数据', value: 'static' },
          { label: '内置指标', value: 'quota' },
          { label: 'API', value: 'api' },
        ],
      },
      { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
      {
        key: 'method',
        name: '请求方式',
        type: 'Select',
        options: [
          { label: 'GET', value: 'get' },
          { label: 'POST', value: 'post' },
        ],
        defaultValue: 'get',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['api'] }],
        },
      },
      {
        key: 'requestUrl',
        name: 'URL',
        type: 'TextArea',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['api'] }],
        },
      },
      {
        key: 'dataQuota',
        name: '数据指标',
        type: 'DataQuotaSelector',
        options: [],
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
        },
      },
      {
        key: 'isPolling',
        name: '定时刷新',
        type: 'Switch',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
        },
      },
      {
        key: 'pollingInterval',
        name: '刷新时间',
        type: 'Number',
        dependencies: {
          items: [{ dependKey: 'isPolling', dependValues: [true] }],
        },
      },
      {
        key: 'dataSource',
        name: '数据源',
        type: 'MonacoEditor',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['static'] }],
        },
      },
    ],
    styleConfig: [],
    eventConfig: [{}],
    componentId: '8043e255-f5c7-4e14-bcaa-49a716807199',
  },
  canvasConfig: {
    width: 1920,
    height: 1080,
    backgroundColor: 'rgba(14,23,31,1)',
  },
  width: 1920,
  height: 1080,
};
