export const page1 = {
  mode: 'edit',
  componentList: [
    {
      name: '柱状图',
      type: 'Bar',
      icon: 'icon-zhuzhuangtu',
      category: 'control',
      config: {
        width: 400,
        height: 238,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '大盘', yAxis: 100 },
          { xAxis: 'xx贷', yAxis: 60 },
          { xAxis: 'xx贷2', yAxis: 30 },
          { xAxis: 'xx贷3', yAxis: 20 },
          { xAxis: 'xx贷4', yAxis: 70 },
          { xAxis: 'xx贷5', yAxis: 40 },
          { xAxis: 'xx贷6', yAxis: 50 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        left: 1498,
        top: 328,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'a7a34a86-655a-4ad7-aa80-a20d65be02a1',
    },
    {
      name: '堆积柱状图',
      type: 'StackBar',
      icon: 'icon-zhuzhuangtu',
      category: 'control',
      config: {
        width: 400,
        height: 234,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '5%', yAxis: '200', series: '大盘' },
          { xAxis: '5%', yAxis: '100', series: 'xx贷' },
          { xAxis: '5%', yAxis: '200', series: 'xx贷款2' },
          { xAxis: '5%-8%', yAxis: '25', series: '大盘' },
          { xAxis: '5%-8%', yAxis: '125', series: 'xx贷' },
          { xAxis: '5%-8%', yAxis: '100', series: 'xx贷款2' },
          { xAxis: '12%-15%', yAxis: '190', series: '大盘' },
          { xAxis: '12%-15%', yAxis: '110', series: 'xx贷' },
          { xAxis: '12%-15%', yAxis: '170', series: 'xx贷款2' },
          { xAxis: '15%-18%', yAxis: '90', series: '大盘' },
          { xAxis: '15%-18%', yAxis: '60', series: 'xx贷' },
          { xAxis: '15%-18%', yAxis: '70', series: 'xx贷款2' },
          { xAxis: '18%-20%', yAxis: '240', series: '大盘' },
          { xAxis: '18%-20%', yAxis: '170', series: 'xx贷' },
          { xAxis: '18%-20%', yAxis: '280', series: 'xx贷款2' },
          { xAxis: '20%-24%', yAxis: '420', series: '大盘' },
          { xAxis: '20%-24%', yAxis: '190', series: 'xx贷' },
          { xAxis: '20%-24%', yAxis: '390', series: 'xx贷款2' },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
          { key: 'series', mapping: '' },
        ],
        left: 1498,
        top: 166,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '84779621-8388-4a1d-a391-87cd93ada99a',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 467,
        height: 41,
        left: 51,
        top: 136,
        zIndex: 45,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929390422-ERkLZiJB.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '7dd6582e-8bc6-4d3f-8521-a9177ebd4ea5',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 1920,
        height: 86,
        left: 0,
        top: 0,
        zIndex: 12,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929391169-7qcX5iQR.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'db4c6579-5041-4d24-ba27-3eafc84b9f27',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 216,
        height: 49,
        text: '贷中运营概要',
        color: 'rgba(255,255,255,1)',
        fontSize: 34,
        left: 848,
        top: 16,
        zIndex: 12,
        componentName: '',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '94cbfce1-2c44-4399-8441-98a497aa0af9',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 1920,
        height: 1069,
        left: 0,
        top: 0,
        zIndex: 0,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929396172-8KkT24og.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '250dc3bd-af6a-484d-a4f8-c2be2bc7546d',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 60,
        height: 50,
        left: 7,
        top: 80,
        zIndex: 14,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929397797-Av8gcZ5j.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '04407146-bc3f-4dce-8beb-611050869bff',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 60,
        height: 50,
        left: 1859,
        top: 80,
        zIndex: 15,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929397112-HZxN3_dO.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '015c52ee-c9ab-4455-9267-071861ac723a',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 530,
        height: 70,
        left: 727,
        top: 704,
        zIndex: 16,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929393526-FqAYJP4f.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '58f90bb8-25f9-416b-a823-7f07c2ff6bef',
    },
    {
      name: '轮播表',
      type: 'ScrollBoard',
      icon: 'icon-lunbobiaoge',
      category: 'control',
      config: {
        width: 662,
        height: 182,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: {
          header: ['列1', '列2', '列3'],
          data: [
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
            [
              '裸体人像检测*置信度0.23',
              '人脸翻拍*置信度0.23',
              '中介背景识别*置信度0.23',
            ],
            [
              '注意力异常*置信度0.23',
              '年龄范围*20-29青年',
              '身份证翻拍*置信度0.34',
            ],
            ['身份证造假*置信度0.23', '拍摄场景*车内', '额度评分*554'],
          ],
        },
        globalConfig: { index: true, rowNum: 5, waitTime: 2000 },
        headerConfig: {
          headerHeight: 30,
          headerBGC: 'rgba(10, 115, 217, 0.2)',
          headerVisible: false,
        },
        lineConfig: {
          oddRowBGC: 'rgba(10, 115, 255, 0)',
          evenRowBGC: 'rgba(9,109,217,0.3)',
        },
        columns: [
          { columnWidth: 50, textStyle: { color: '#fff', fontSize: 14 } },
          { columnWidth: 200, textStyle: { color: '#fff', fontSize: 14 } },
          { columnWidth: 200, textStyle: { color: '#fff', fontSize: 14 } },
          { columnWidth: 200, textStyle: { color: '#fff', fontSize: 14 } },
        ],
        left: 672,
        top: 789,
        zIndex: 17,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'globalConfig',
          name: '全局设定',
          type: 'Group',
          config: [
            { key: 'index', name: '显示序列号', type: 'Switch' },
            { key: 'rowNum', name: '表格行数', type: 'Number' },
            { key: 'waitTime', name: '轮播时间', type: 'Number' },
          ],
        },
        {
          key: 'headerConfig',
          name: '表头',
          type: 'Group',
          config: [
            { key: 'headerVisible', name: '是否显示', type: 'Switch' },
            { key: 'headerHeight', name: '表头行高', type: 'Number' },
            { key: 'headerBGC', name: '背景颜色', type: 'Color' },
          ],
        },
        {
          key: 'lineConfig',
          name: '行配置',
          type: 'Group',
          config: [
            { key: 'oddRowBGC', name: '奇数行背景色', type: 'Color' },
            { key: 'evenRowBGC', name: '偶数行背景色', type: 'Color' },
          ],
        },
        {
          key: 'columns',
          name: '自定义列',
          type: 'TabList',
          initialValue: {
            columnWidth: 200,
            textStyle: { color: '#fff', fontSize: 12 },
          },
          config: [
            { key: 'columnWidth', name: '列宽度', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '75b24e49-9530-432c-ade9-7a371de2dde3',
    },
    {
      name: '中国地图',
      type: 'ChinaMap',
      icon: 'icon-zhuzhuangtu',
      category: 'CHART',
      config: { width: 1126, height: 835, left: 455, top: 98, zIndex: 1 },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'title', name: '文字', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'options', name: '选项', type: 'List' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'fecdd452-9bbd-4796-b179-25d58f16450b',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 246,
        height: 53,
        text: '贷中风险模型监控',
        color: 'rgba(254, 250, 250, 1)',
        fontSize: 30,
        left: 888,
        top: 715,
        zIndex: 16,
        componentName: '',
        backgroundColor: 'rgba(158, 38, 38, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'ca00d6a0-c346-4a75-9d9f-c19672f842ef',
    },
    {
      name: '折线图',
      type: 'Line',
      chartType: 'line',
      icon: 'icon-xianxingtu',
      category: 'CHART',
      config: {
        width: 400,
        height: 214,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '2022.1', yAxis: 1300 },
          { xAxis: '2022.2', yAxis: 1500 },
          { xAxis: '2022.3', yAxis: 1600 },
          { xAxis: '2022.4', yAxis: 1200 },
          { xAxis: '2022.5', yAxis: 1400 },
          { xAxis: '2022.6', yAxis: 1600 },
          { xAxis: '2022.7', yAxis: 1400 },
          { xAxis: '2022.8', yAxis: 1100 },
          { xAxis: '2022.9', yAxis: 1300 },
          { xAxis: '2022.10', yAxis: 1400 },
          { xAxis: '2022.11', yAxis: 1700 },
          { xAxis: '2022.12', yAxis: 1800 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 1498,
        top: 537,
        zIndex: 16,
        series: [
          {
            areaStyle: {
              color:
                'linear-gradient(90deg, RGBA(2,0,36,1) 0%, rgba(0,212,255,1) 100%)',
            },
          },
        ],
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
        {
          key: 'grid',
          name: '网格',
          type: 'Group',
          config: [
            { key: 'left', name: '左边距', type: 'Number' },
            { key: 'top', name: '上边距', type: 'Number' },
            { key: 'right', name: '右边距', type: 'Number' },
            { key: 'bottom', name: '下边距', type: 'Number' },
          ],
        },
        {
          key: 'series',
          name: '系列',
          type: 'TabList',
          config: [
            {
              key: 'lineStyle',
              name: '线条样式',
              type: 'Group',
              config: [
                { key: 'color', name: '线条颜色', type: 'Color' },
                { key: 'width', name: '线条宽度', type: 'Number' },
                {
                  key: 'type',
                  name: '线条类型',
                  type: 'Select',
                  options: [
                    { label: '实线', value: 'solid' },
                    { label: '虚线', value: 'dashed' },
                  ],
                },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'itemStyle',
              name: '折线拐点样式',
              type: 'Group',
              config: [
                { key: 'color', name: '折线拐点颜色', type: 'Color' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'areaStyle',
              name: '折线区域样式',
              type: 'Group',
              config: [
                { key: 'color', name: '区域颜色', type: 'GradientColor' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            { key: 'smooth', name: '平滑曲线', type: 'Number' },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '3c587607-feb8-4800-ac45-0f0ddb6ae732',
    },
    {
      name: '折线图',
      type: 'Line',
      chartType: 'line',
      icon: 'icon-xianxingtu',
      category: 'CHART',
      config: {
        width: 400,
        height: 214,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '2022.1', yAxis: 5610 },
          { xAxis: '2022.2', yAxis: 4561 },
          { xAxis: '2022.3', yAxis: 4358 },
          { xAxis: '2022.4', yAxis: 6725 },
          { xAxis: '2022.5', yAxis: 6871 },
          { xAxis: '2022.6', yAxis: 5514 },
          { xAxis: '2022.7', yAxis: 3467 },
          { xAxis: '2022.8', yAxis: 3800 },
          { xAxis: '2022.9', yAxis: 8700 },
          { xAxis: '2022.10', yAxis: 4974 },
          { xAxis: '2022.11', yAxis: 6800 },
          { xAxis: '2022.12', yAxis: 8647 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 1498,
        top: 759,
        zIndex: 16,
        series: [
          {
            areaStyle: {
              color:
                'linear-gradient(90deg, RGBA(2,0,36,1) 0%, rgba(0,212,255,1) 100%)',
            },
          },
        ],
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
        {
          key: 'grid',
          name: '网格',
          type: 'Group',
          config: [
            { key: 'left', name: '左边距', type: 'Number' },
            { key: 'top', name: '上边距', type: 'Number' },
            { key: 'right', name: '右边距', type: 'Number' },
            { key: 'bottom', name: '下边距', type: 'Number' },
          ],
        },
        {
          key: 'series',
          name: '系列',
          type: 'TabList',
          config: [
            {
              key: 'lineStyle',
              name: '线条样式',
              type: 'Group',
              config: [
                { key: 'color', name: '线条颜色', type: 'Color' },
                { key: 'width', name: '线条宽度', type: 'Number' },
                {
                  key: 'type',
                  name: '线条类型',
                  type: 'Select',
                  options: [
                    { label: '实线', value: 'solid' },
                    { label: '虚线', value: 'dashed' },
                  ],
                },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'itemStyle',
              name: '折线拐点样式',
              type: 'Group',
              config: [
                { key: 'color', name: '折线拐点颜色', type: 'Color' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            {
              key: 'areaStyle',
              name: '折线区域样式',
              type: 'Group',
              config: [
                { key: 'color', name: '区域颜色', type: 'GradientColor' },
                { key: 'opacity', name: '透明度', type: 'Number' },
              ],
            },
            { key: 'smooth', name: '平滑曲线', type: 'Number' },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '74feec66-debb-4e02-92b2-b8a42cbc03a5',
    },
    {
      name: '环形图',
      type: 'RingChart',
      chartType: 'pie',
      icon: 'icon-shanxingtu',
      category: 'CHART',
      config: {
        width: 473,
        height: 440,
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        dataSource: [
          { xAxis: '合规投诉', yAxis: 46648 },
          { xAxis: '催收投诉', yAxis: 6680 },
          { xAxis: '产品服务投诉', yAxis: 4435 },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
        ],
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 55,
        top: 200,
        zIndex: 18,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '871d825d-d6a3-4091-b479-fac1a6463155',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 137,
        height: 29,
        text: '产品各类投诉组成',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 16,
        left: 86,
        top: 142,
        zIndex: 46,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '31f3ddb7-fc90-42bf-94b7-fe16e8a0cdbc',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 400,
        height: 41,
        left: 1498,
        top: 113,
        zIndex: 45,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929390422-ERkLZiJB.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'd82b2213-b6b1-4d98-a0b1-f649c1520d9f',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 1858,
        height: 61,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929391862-NoETDPhi.png',
        left: 40,
        top: 1001,
        zIndex: 20,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: '31447d5b-7895-4606-a43c-475a848d448b',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 147,
        height: 31,
        text: '各项指标分析',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 16,
        left: 1528,
        top: 121,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'b369f4aa-a807-432a-a7c6-8cab2fa62fdf',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 85,
        height: 27,
        text: '利率分布',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 1658,
        top: 350,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '1c64daaa-4bb3-42b8-961e-24e99fcc0f07',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 139,
        height: 27,
        text: '各类产品市场占有量',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 1628,
        top: 518,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: 'd2b515b0-29d1-4ac7-a5d1-b432104c6a77',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 172,
        height: 27,
        text: '2022年大盘各月贷款人数',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 1609,
        top: 745,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '8a5c033b-95c2-4b49-8eb8-b4e9919715ab',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 243,
        height: 27,
        text: '2022年其他金融产品各月贷款人数',
        color: 'rgba(255, 255, 255, 0.79)',
        fontSize: 14,
        left: 1588,
        top: 972,
        zIndex: 46,
        backgroundColor: 'rgba(246, 244, 244, 0)',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '4ebd6ed8-1286-46b8-b68b-d77adab72829',
    },
    {
      name: '垂直堆叠柱状图',
      type: 'VerticalStackBar',
      chartType: 'bar',
      icon: 'icon-zhuzhuangduidietu',
      category: 'CHART',
      config: {
        width: 397,
        height: 276,
        dataSource: [
          { xAxis: '2022.1', yAxis: 200, series: '1万以内' },
          { xAxis: '2022.1', yAxis: 100, series: '1-3万' },
          { xAxis: '2022.1', yAxis: 200, series: '3-5万' },
          { xAxis: '2022.1', yAxis: 200, series: '5-10万' },
          { xAxis: '2022.1', yAxis: 200, series: '10-20万' },
          { xAxis: '2022.1', yAxis: 200, series: '20-50万' },
          { xAxis: '2022.2', yAxis: 160, series: '1万以内' },
          { xAxis: '2022.2', yAxis: 100, series: '1-3万' },
          { xAxis: '2022.2', yAxis: 140, series: '3-5万' },
          { xAxis: '2022.2', yAxis: 240, series: '5-10万' },
          { xAxis: '2022.2', yAxis: 180, series: '10-20万' },
          { xAxis: '2022.2', yAxis: 120, series: '20-50万' },
          { xAxis: '2022.3', yAxis: 140, series: '1万以内' },
          { xAxis: '2022.3', yAxis: 180, series: '1-3万' },
          { xAxis: '2022.3', yAxis: 94, series: '3-5万' },
          { xAxis: '2022.3', yAxis: 156, series: '5-10万' },
          { xAxis: '2022.3', yAxis: 184, series: '10-20万' },
          { xAxis: '2022.3', yAxis: 60, series: '20-50万' },
          { xAxis: '2022.4', yAxis: 200, series: '1万以内' },
          { xAxis: '2022.4', yAxis: 180, series: '1-3万' },
          { xAxis: '2022.4', yAxis: 68, series: '3-5万' },
          { xAxis: '2022.4', yAxis: 178, series: '5-10万' },
          { xAxis: '2022.4', yAxis: 197, series: '10-20万' },
          { xAxis: '2022.4', yAxis: 295, series: '20-50万' },
          { xAxis: '2022.5', yAxis: 87, series: '1万以内' },
          { xAxis: '2022.5', yAxis: 186, series: '1-3万' },
          { xAxis: '2022.5', yAxis: 125, series: '3-5万' },
          { xAxis: '2022.5', yAxis: 194, series: '5-10万' },
          { xAxis: '2022.5', yAxis: 150, series: '10-20万' },
          { xAxis: '2022.5', yAxis: 123, series: '20-50万' },
          { xAxis: '2022.6', yAxis: 187, series: '1万以内' },
          { xAxis: '2022.6', yAxis: 154, series: '1-3万' },
          { xAxis: '2022.6', yAxis: 111, series: '3-5万' },
          { xAxis: '2022.6', yAxis: 279, series: '5-10万' },
          { xAxis: '2022.6', yAxis: 240, series: '10-20万' },
          { xAxis: '2022.6', yAxis: 147, series: '20-50万' },
        ],
        dataMapping: [
          { key: 'xAxis', mapping: '' },
          { key: 'yAxis', mapping: '' },
          { key: 'series', mapping: '' },
        ],
        dataType: 'static',
        requestUrl:
          'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
        grid: { left: 30, right: 30, top: 30, bottom: 30 },
        legend: {
          horizontalPosition: 'auto',
          verticalPosition: 'auto',
          orient: 'horizontal',
          padding: 30,
          itemGap: 20,
          textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
        },
        left: 71,
        top: 688,
        zIndex: 26,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        {
          key: 'legend',
          name: '图例',
          type: 'Group',
          config: [
            {
              key: 'horizontalPosition',
              name: '水平位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '左对齐', value: 'left' },
                { label: '居中对齐', value: 'center' },
                { label: '右对齐', value: 'right' },
              ],
            },
            {
              key: 'verticalPosition',
              name: '竖直位置',
              type: 'Select',
              options: [
                { label: '自动', value: 'auto' },
                { label: '顶部对齐', value: 'top' },
                { label: '居中对齐', value: 'center' },
                { label: '底部对齐', value: 'bottom' },
              ],
            },
            {
              key: 'orient',
              name: '朝向',
              type: 'Select',
              options: [
                { label: '垂直', value: 'vertical' },
                { label: '水平', value: 'horizontal' },
              ],
            },
            { key: 'padding', name: '内边距', type: 'Number' },
            { key: 'itemGap', name: '图例项间距', type: 'Number' },
            {
              key: 'textStyle',
              name: '文本样式',
              type: 'Group',
              config: [
                { key: 'color', name: '颜色', type: 'Color' },
                {
                  key: 'fontWeight',
                  name: '字体粗细',
                  type: 'Select',
                  options: [
                    { label: 'Normal', value: 'normal' },
                    { label: 'Bold', value: 'bold' },
                    { label: 'Bolder', value: 'bolder' },
                    { label: 100, value: 100 },
                    { label: 200, value: 200 },
                    { label: 300, value: 300 },
                    { label: 400, value: 400 },
                    { label: 500, value: 500 },
                    { label: 600, value: 600 },
                    { label: 700, value: 700 },
                    { label: 800, value: 800 },
                    { label: 900, value: 900 },
                  ],
                },
                { key: 'fontSize', name: '字号', type: 'Number' },
              ],
            },
          ],
        },
      ],
      dataConfig: [
        {
          key: 'dataType',
          name: '数据类型',
          type: 'Select',
          options: [
            { label: '静态数据', value: 'static' },
            { label: '内置指标', value: 'quota' },
            { label: 'API', value: 'api' },
          ],
        },
        { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
        {
          key: 'method',
          name: '请求方式',
          type: 'Select',
          options: [
            { label: 'GET', value: 'get' },
            { label: 'POST', value: 'post' },
          ],
          defaultValue: 'get',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'requestUrl',
          name: 'URL',
          type: 'TextArea',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['api'] }],
          },
        },
        {
          key: 'dataQuota',
          name: '数据指标',
          type: 'DataQuotaSelector',
          options: [],
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
          },
        },
        {
          key: 'isPolling',
          name: '定时刷新',
          type: 'Switch',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
          },
        },
        {
          key: 'pollingInterval',
          name: '刷新时间',
          type: 'Number',
          dependencies: {
            items: [{ dependKey: 'isPolling', dependValues: [true] }],
          },
        },
        {
          key: 'dataSource',
          name: '数据源',
          type: 'MonacoEditor',
          dependencies: {
            items: [{ dependKey: 'dataType', dependValues: ['static'] }],
          },
        },
      ],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '文字大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '21a7ea9c-4b9b-4882-b130-bacd64ba4062',
    },
    {
      name: '图片',
      type: 'Img',
      icon: 'icon-yduifuxuankuangxuanzhong',
      category: 'control',
      config: {
        width: 467,
        height: 41,
        left: 69,
        top: 634,
        zIndex: 45,
        imgUrl:
          'https://cdn-upload.datav.aliyun.com/upload/download/1675929390422-ERkLZiJB.png',
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'imgUrl', name: '图片', type: 'Image' },
      ],
      dataConfig: [],
      styleConfig: [],
      eventConfig: [],
      componentId: 'adb3ebff-93a7-4c12-90e7-39c9b1ecc4ef',
    },
    {
      name: '通用标题',
      type: 'Title',
      icon: 'icon-biaoti',
      category: 'information',
      config: {
        width: 137,
        height: 29,
        text: '额度分布',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: 16,
        left: 112,
        top: 641,
        zIndex: 46,
      },
      baseConfig: [
        { key: 'componentName', name: '名称', type: 'Text' },
        { key: 'width', name: '宽度', type: 'Number' },
        { key: 'height', name: '高度', type: 'Number' },
        { key: 'top', name: '纵向偏移', type: 'Number' },
        { key: 'left', name: '横向偏移', type: 'Number' },
        { key: 'zIndex', name: '组件层级', type: 'Number' },
        { key: 'text', name: '标题', type: 'Text' },
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'backgroundColor', name: '背景颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      dataConfig: [{ key: 'text', name: '标题', type: 'Text' }],
      styleConfig: [
        { key: 'color', name: '标题颜色', type: 'Color' },
        { key: 'fontSize', name: '字体大小', type: 'Number' },
      ],
      eventConfig: [{}],
      componentId: '6c441a5d-53c1-4c9c-b04b-743c69c7a377',
    },
  ],
  curComponentConfig: {
    name: '垂直堆叠柱状图',
    type: 'VerticalStackBar',
    chartType: 'bar',
    icon: 'icon-zhuzhuangduidietu',
    category: 'CHART',
    config: {
      width: 397,
      height: 276,
      dataSource: [
        { xAxis: '2022.1', yAxis: 200, series: '1万以内' },
        { xAxis: '2022.1', yAxis: 100, series: '1-3万' },
        { xAxis: '2022.1', yAxis: 200, series: '3-5万' },
        { xAxis: '2022.1', yAxis: 200, series: '5-10万' },
        { xAxis: '2022.1', yAxis: 200, series: '10-20万' },
        { xAxis: '2022.1', yAxis: 200, series: '20-50万' },
        { xAxis: '2022.2', yAxis: 160, series: '1万以内' },
        { xAxis: '2022.2', yAxis: 100, series: '1-3万' },
        { xAxis: '2022.2', yAxis: 140, series: '3-5万' },
        { xAxis: '2022.2', yAxis: 240, series: '5-10万' },
        { xAxis: '2022.2', yAxis: 180, series: '10-20万' },
        { xAxis: '2022.2', yAxis: 120, series: '20-50万' },
        { xAxis: '2022.3', yAxis: 140, series: '1万以内' },
        { xAxis: '2022.3', yAxis: 180, series: '1-3万' },
        { xAxis: '2022.3', yAxis: 94, series: '3-5万' },
        { xAxis: '2022.3', yAxis: 156, series: '5-10万' },
        { xAxis: '2022.3', yAxis: 184, series: '10-20万' },
        { xAxis: '2022.3', yAxis: 60, series: '20-50万' },
        { xAxis: '2022.4', yAxis: 200, series: '1万以内' },
        { xAxis: '2022.4', yAxis: 180, series: '1-3万' },
        { xAxis: '2022.4', yAxis: 68, series: '3-5万' },
        { xAxis: '2022.4', yAxis: 178, series: '5-10万' },
        { xAxis: '2022.4', yAxis: 197, series: '10-20万' },
        { xAxis: '2022.4', yAxis: 295, series: '20-50万' },
        { xAxis: '2022.5', yAxis: 87, series: '1万以内' },
        { xAxis: '2022.5', yAxis: 186, series: '1-3万' },
        { xAxis: '2022.5', yAxis: 125, series: '3-5万' },
        { xAxis: '2022.5', yAxis: 194, series: '5-10万' },
        { xAxis: '2022.5', yAxis: 150, series: '10-20万' },
        { xAxis: '2022.5', yAxis: 123, series: '20-50万' },
        { xAxis: '2022.6', yAxis: 187, series: '1万以内' },
        { xAxis: '2022.6', yAxis: 154, series: '1-3万' },
        { xAxis: '2022.6', yAxis: 111, series: '3-5万' },
        { xAxis: '2022.6', yAxis: 279, series: '5-10万' },
        { xAxis: '2022.6', yAxis: 240, series: '10-20万' },
        { xAxis: '2022.6', yAxis: 147, series: '20-50万' },
      ],
      dataMapping: [
        { key: 'xAxis', mapping: '' },
        { key: 'yAxis', mapping: '' },
        { key: 'series', mapping: '' },
      ],
      dataType: 'static',
      requestUrl:
        'https://www.fastmock.site/mock/37597c10a5a6e25ce79c38731203c4fd/maliang/indicator/interest/rate/distribution',
      grid: { left: 30, right: 30, top: 30, bottom: 30 },
      legend: {
        horizontalPosition: 'auto',
        verticalPosition: 'auto',
        orient: 'horizontal',
        padding: 30,
        itemGap: 20,
        textStyle: { color: '#fff', fontWeight: 300, fontSize: 18 },
      },
      left: 71,
      top: 688,
      zIndex: 26,
    },
    baseConfig: [
      { key: 'componentName', name: '名称', type: 'Text' },
      { key: 'width', name: '宽度', type: 'Number' },
      { key: 'height', name: '高度', type: 'Number' },
      { key: 'top', name: '纵向偏移', type: 'Number' },
      { key: 'left', name: '横向偏移', type: 'Number' },
      { key: 'zIndex', name: '组件层级', type: 'Number' },
      {
        key: 'legend',
        name: '图例',
        type: 'Group',
        config: [
          {
            key: 'horizontalPosition',
            name: '水平位置',
            type: 'Select',
            options: [
              { label: '自动', value: 'auto' },
              { label: '左对齐', value: 'left' },
              { label: '居中对齐', value: 'center' },
              { label: '右对齐', value: 'right' },
            ],
          },
          {
            key: 'verticalPosition',
            name: '竖直位置',
            type: 'Select',
            options: [
              { label: '自动', value: 'auto' },
              { label: '顶部对齐', value: 'top' },
              { label: '居中对齐', value: 'center' },
              { label: '底部对齐', value: 'bottom' },
            ],
          },
          {
            key: 'orient',
            name: '朝向',
            type: 'Select',
            options: [
              { label: '垂直', value: 'vertical' },
              { label: '水平', value: 'horizontal' },
            ],
          },
          { key: 'padding', name: '内边距', type: 'Number' },
          { key: 'itemGap', name: '图例项间距', type: 'Number' },
          {
            key: 'textStyle',
            name: '文本样式',
            type: 'Group',
            config: [
              { key: 'color', name: '颜色', type: 'Color' },
              {
                key: 'fontWeight',
                name: '字体粗细',
                type: 'Select',
                options: [
                  { label: 'Normal', value: 'normal' },
                  { label: 'Bold', value: 'bold' },
                  { label: 'Bolder', value: 'bolder' },
                  { label: 100, value: 100 },
                  { label: 200, value: 200 },
                  { label: 300, value: 300 },
                  { label: 400, value: 400 },
                  { label: 500, value: 500 },
                  { label: 600, value: 600 },
                  { label: 700, value: 700 },
                  { label: 800, value: 800 },
                  { label: 900, value: 900 },
                ],
              },
              { key: 'fontSize', name: '字号', type: 'Number' },
            ],
          },
        ],
      },
    ],
    dataConfig: [
      {
        key: 'dataType',
        name: '数据类型',
        type: 'Select',
        options: [
          { label: '静态数据', value: 'static' },
          { label: '内置指标', value: 'quota' },
          { label: 'API', value: 'api' },
        ],
      },
      { key: 'dataMapping', name: '数据接口', type: 'DataMapping' },
      {
        key: 'method',
        name: '请求方式',
        type: 'Select',
        options: [
          { label: 'GET', value: 'get' },
          { label: 'POST', value: 'post' },
        ],
        defaultValue: 'get',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['api'] }],
        },
      },
      {
        key: 'requestUrl',
        name: 'URL',
        type: 'TextArea',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['api'] }],
        },
      },
      {
        key: 'dataQuota',
        name: '数据指标',
        type: 'DataQuotaSelector',
        options: [],
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['quota'] }],
        },
      },
      {
        key: 'isPolling',
        name: '定时刷新',
        type: 'Switch',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['quota', 'api'] }],
        },
      },
      {
        key: 'pollingInterval',
        name: '刷新时间',
        type: 'Number',
        dependencies: {
          items: [{ dependKey: 'isPolling', dependValues: [true] }],
        },
      },
      {
        key: 'dataSource',
        name: '数据源',
        type: 'MonacoEditor',
        dependencies: {
          items: [{ dependKey: 'dataType', dependValues: ['static'] }],
        },
      },
    ],
    styleConfig: [
      { key: 'color', name: '标题颜色', type: 'Color' },
      { key: 'fontSize', name: '文字大小', type: 'Number' },
    ],
    eventConfig: [{}],
    componentId: '21a7ea9c-4b9b-4882-b130-bacd64ba4062',
  },
  canvasConfig: {
    width: 1920,
    height: 1080,
    backgroundColor: 'rgba(14,23,31,1)',
  },
  width: 1920,
  height: 1080,
};
